### PR TITLE
add optional label to form label

### PR DESCRIPTION
**Pull request by LukaszKorzybski**
Not sure what is the preferred approach to CSS classes so done it like that but please correct me if we do it differently, I though also about:

```
<label class="form-label">asdsada <span class="optional">(optional)</span></label> 

<label class="form-label form-label-optional">asdsada <span>(optional)</span></label>

<label class="form-label-optional">asdsada <span class="optional">(optional)</span></label>
```

### CODE REVIEW

**Comment by vygis** [comment]
@LukaszKorzybski I would suggest using an existing bootstrap class `text-muted` which grays out the text. Also, not sure if font-weight should belong to the class. Are you sure that you want the main label to be bold, and the optional part normal weight? I've just added some stuff for a different usecase which is a quite similar, have a look here: [http://plnkr.co/edit/8pzoZ2?p=preview](http://plnkr.co/edit/8pzoZ2?p=preview)

**Comment by vygis** [comment]
If we need to have the 'optional' spans to have normal weight, I'd suggest using Boostraps `text-muted` and to add the following into `forms.css`:
```
label {
  .text-muted {
    font-weight: normal;
  }
}
```

**Comment by LukaszKorzybski** [comment]
Not sure about the font weight I just followed what was in the ux design
but actually the label on ux is also normal weight so probably both should
be bold as per styleguide?

**Comment by LukaszKorzybski** [comment]
Ok thanks, I think now if shuld be bold probably as the ux screen was i
guess not precise as to font weight?

**Comment by vygis** [comment]
Cool. So I'd say use `.text-muted`. In this case we don't need the css changes. If you feel like it, feel free to add the example in the docs, updating it to use this class :)

**Pull request merged**
